### ISSUE TITLE
Interactive Feature is Unusable

### ISSUE THREAD

**Issue by mlr-msft** [FStarLang/VimFStar#12]
I've been looking into the interactive feature of *VimFStar* and it appears unusable.

- It seems to have never have been written to support Windows outside of *cygwin* (e.g. lines of code like `let s:path = system("echo $PATH")` suggests this to be the case).
- I've tried using it on a Debian Jessie system. Pressing `<F2>` per the instructions results in the plugin never leaving the `Always busy` state.
- *VimFStar* provides no feedback regarding what's wrong nor does there seem to be any meaningful diagnostic code.

I've begun an attempt to address these issues. Before I get too deep into it, I wanted to ask:

- Does anyone currently use this feature? If nobody responds within a reasonable time period, I will assume not.
- If yes, is there any critical portion that needs to be preserved? I anticipate modifying a large amount of code in my effort to understand, fix, and inject usability into this feature; I don't want to unintentionally harm anyone's productivity in the process.

I will be making all of my changes in [a fork](https://github.com/mlr-msft/VimFStar) and will produce a pull request when I believe I have something of quality.

Thanks in advance for any comments. :smile_cat:

**Comment by catalin-hritcu** [comment]
@SimonForest originally implemented this, but I don't think is still using it (or F*). @ngrimm: are you using it?

**Comment by ngrimm** [comment]
I'm currently not using the feature but I was using it before and plan to use it again.
Of course I'm looking forward to possible improvements, so feel free to make any modifications.

**Comment by mlr-msft** [comment]
It took a while but I've learned that the interactive mode currently requires Cygwin to function. I use a native build of Vim. I'll document this in the README and close out the issue.
